### ISSUE TITLE
.screens command fails to display image

### ISSUE THREAD

**Issue by Valastiri** [flybywiresim/discord-bot#93] opened 2021-11-14 18:39 UTC
Here's a sample of what happens (in our #discord-bot channel) 
![image](https://user-images.githubusercontent.com/1619968/141694084-610c67f6-abdc-4ffe-8c92-49dbf9ebb3d5.png)

The image is missing even though the command has a URL in place.

Could be an issue with using the `media.discordapp` vs `cdn.discordapp` link as discussed further in the channel as well.

Would still need to be fixed however :) -- thanks!

**Comment by benw202** [comment] 2021-11-14 22:11
I have just tested this and .screens is working for me. I am not sure what the issue is yet but will look into it.

I will keep this issue open for now and if you spot it happen again, comment here with command name and time. That would be very helpful!

**Comment by oim1** [comment] 2021-11-17 01:08
Just tested this as well, works fine for me.

**Comment by benw202** [comment] 2021-11-24 22:04
I am closing this issue as we haven't had an issue with .screens since. 

It may have been a Discord issue. Feel free to re-open if you see it happen again!

**Closed by benw202** 2021-11-24 22:04 UTC
